### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by santhosh2442** [Mikopet/InSSpector#1]
Not Found
The requested URL /web/sd was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 139.59.36.251 Port 80

When i click Search And Destroy On The Right Top it gets redirected to this site ....

**Comment by Mikopet** [comment]
How your config file looks out?
The image directory has good permissions?

**Comment by Mikopet** [comment]
Ah I see now. I think this is an issue in your webserver configuration
